fos_rest:
  param_fetcher_listener: true
  body_listener: true
  exception:
    enabled: true

  body_converter:
    enabled: true
    validate: true
    validation_errors_argument: violations
  view:
    view_response_listener:  true

  # les valeurs a nulle sont quand meme passer
  serializer:
    serialize_null: true
  #    exception:
  #        codes:
  #            App\Exception\MyException: 403
  #        messages:
  #            App\Exception\MyException: Forbidden area.
  format_listener:
    rules:
      - { path: ^/, fallback_format: json, priorities: [ json ] }
